### ISSUE TITLE
RDF research

### ISSUE THREAD

**Issue by cipriancus** [cipriancus/CryMa#19]

**Comment by cocageorgiana** [comment]
-Has no view for people
-can easily shape the graphs
-is used instead of a distributed database
-easier information structure
-can insert RDFA into HTML and then convert to any RDF like json, xml
**# RDF - Examples of Use**
Describing properties for shopping items, such as price and availability
Describing time schedules for web events
Describing information about web pages (content, author, created and modified date)
Describing content and rating for web pictures
Describing electronic libraries
